import { AffirmationsCardData, AffirmationsCategories, AffirmationsFormats } from "../interfaces/affirmationsData";
import { COLORS } from "./theme";

export const affirmationsCardData: AffirmationsCardData[] = [
    {
        id: "generalAffirmation1",
        title: "affirmations.general1",
        description: "Affirmation for free users of general category text",
        category: AffirmationsCategories.GENERAL,
        color: COLORS.weeklyColor1,
        affirmationFormat: AffirmationsFormats.TEXT,
        image: require("@/src/assets/images/onBoard/onBoarding1.webp"),
    },
    {
        id: "generalAffirmation2",
        title: "affirmations.general2",
        description: "Affirmation for free users of general category audio",
        category: AffirmationsCategories.GENERAL,
        color: COLORS.weeklyColor2,
        affirmationFormat: AffirmationsFormats.AUDIO,
        image: require("@/src/assets/images/onBoard/onBoarding2.webp"),
    },
    {
        id: "selfLoveAffirmation1",
        title: "affirmations.selfLove1",
        description: "Embrace who you are with kindness and understanding. Cultivate inner peace by accepting your strengths and imperfections, fostering a deeper sense of self-worth and personal growth",
        category: AffirmationsCategories.SELF_LOVE,
        color: COLORS.weeklyColor3,
        affirmationFormat: AffirmationsFormats.AUDIO,
        image: require("@/src/assets/images/affirmations/self-acceptance.webp"),
    },
    {
        id: "selfLoveAffirmation2",
        title: "affirmations.selfLove2",
        description: "Self-esteem is the foundation of a healthy self-image. It is the belief in your own worth and abilities, and the confidence to pursue your goals and dreams",
        category: AffirmationsCategories.SELF_LOVE,
        color: COLORS.weeklyColor4,
        affirmationFormat: AffirmationsFormats.TEXT,
        image: require("@/src/assets/images/affirmations/self-esteem.webp"),
    },
    {
        id: "abundanceAffirmation1",
        title: "affirmations.abundance1",
        description: "Manifesting abundance is about attracting prosperity and success into your life. It is the belief that you are worthy of abundance and the ability to create the life you desire",
        category: AffirmationsCategories.ABUNDANCE,
        color: COLORS.weeklyColor5,
        affirmationFormat: AffirmationsFormats.TEXT,
        image: require("@/src/assets/images/affirmations/manifesting_abundance.webp"),
    },
    {
        id: "abundanceAffirmation2",
        title: "affirmations.abundance2",
        description: "Believing in limitless opportunities and focusing on growth, gratitude, and success.",
        category: AffirmationsCategories.ABUNDANCE,
        color: COLORS.weeklyColor6,
        affirmationFormat: AffirmationsFormats.AUDIO,
        image: require("@/src/assets/images/affirmations/abundance_mindset.webp"),
    },
    {
        id: "confidenceAffirmation1",
        title: "affirmations.confidence1",
        description: "Embrace who you are with kindness and understanding. Cultivate inner peace by accepting your strengths and imperfections, fostering a deeper sense of self-worth and personal growth",
        category: AffirmationsCategories.CONFIDENCE,
        color: COLORS.weeklyColor7,
        affirmationFormat: AffirmationsFormats.TEXT,
        image: require("@/src/assets/images/affirmations/fearless.webp"),
    },
    {
        id: "confidenceAffirmation2",
        title: "affirmations.confidence2",
        description: "Unlock your potential by believing in yourself and your abilities. Embrace your strengths and overcome your fears to achieve your goals and dreams",
        category: AffirmationsCategories.CONFIDENCE,
        color: COLORS.weeklyColor8,
        affirmationFormat: AffirmationsFormats.AUDIO,
        image: require("@/src/assets/images/affirmations/unlock_potential.webp"),
    },
    {
        id: "healthAffirmation1",
        title: "affirmations.health1",
        description: "Take care of your mental health by practicing self-care, mindfulness, and positive thinking. Nurture your emotional well-being and cultivate a sense of inner peace and balance",
        category: AffirmationsCategories.HEALTH,
        color: COLORS.weeklyColor9,
        affirmationFormat: AffirmationsFormats.TEXT,
        image: require("@/src/assets/images/affirmations/improve_mental_health.webp"),
    },
    {
        id: "healthAffirmation2",
        title: "affirmations.health2",
        description: "Nourish your body with healthy food, exercise, and rest. Strengthen your physical health and well-being by taking care of your body and mind",
        category: AffirmationsCategories.HEALTH,
        color: COLORS.weeklyColor10,
        affirmationFormat: AffirmationsFormats.AUDIO,
        image: require("@/src/assets/images/affirmations/healthy_body.webp"),
    },
    {
        id: "relationshipsAffirmation1",
        title: "affirmations.relationships1",
        description: "Resolve conflicts and build stronger relationships by practicing empathy, active listening, and effective communication. Foster understanding, trust, and connection with others",
        category: AffirmationsCategories.RELATIONSHIPS,
        color: COLORS.weeklyColor11,
        affirmationFormat: AffirmationsFormats.AUDIO,
        image: require("@/src/assets/images/affirmations/effective_communication.webp"),
    },
    {
        id: "relationshipsAffirmation2",
        title: "affirmations.relationships2",
        description: "Conflict resolution is about finding common ground, understanding different perspectives, and working together to find solutions. It is the ability to resolve conflicts peacefully and build stronger relationships",
        category: AffirmationsCategories.RELATIONSHIPS,
        color: COLORS.weeklyColor12,
        affirmationFormat: AffirmationsFormats.TEXT,
        image: require("@/src/assets/images/affirmations/conflict_resolution.webp"),
    },
]